---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rdvgfuhy/repositories/html-python-flask/
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp svm_pickle.pkl $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r templates $DEPLOYPATH